# Generated by Django 4.2.5 on 2023-10-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.PositiveIntegerField()),
                ('adress', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(default='', upload_to='profile_pic/')),
                ('usertype', models.CharField(default='buyer', max_length=50)),
            ],
        ),
    ]
