# Generated by Django 4.2.5 on 2023-10-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categories', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=60)),
                ('product_subcategories', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Shoes', 'Shoes')], max_length=60)),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=60)),
                ('product_size', models.CharField(max_length=16)),
                ('product_price', models.PositiveIntegerField()),
                ('product_decription', models.TextField()),
                ('product_information', models.TextField()),
                ('product_pic', models.ImageField(upload_to='product_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
